language: ruby
rvm:
  - 2.3.1
gemfile:
  - Gemfile
sudo: false
script:
  - bundle exec rails db:test:prepare
  - bundle exec rails test
notifications:
  email:
  - marcel@bluepanel.org

addons:
  code_climate:
    repo_token: b1924d24d05433e0be72b1aed6a199669e882b1061b5bd8fae581b6934311d30
