defaults: &defaults
  registration_is_enabled: false
  count_of_posts_on_index_page: 3
  post_preview_sign_length: 250
  gravatar_email: marcel@bluepanel.org
  github_username: mawiegand
  linkedin_username: marcelwiegand
  google_plus_username: MarcelWiegand
  twitter_username: BP_doubleU

development:
  <<: *defaults
  registration_is_enabled: true

test:
  <<: *defaults
  registration_is_enabled: true

production:
  <<: *defaults